In [10]:
import numpy as np

In [11]:
identity_matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
matrix = np.random.random_integers(1, 10, size=(3, 3))

C:\Users\szymo\AppData\Local\Temp\ipykernel_13512\918141746.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  matrix = np.random.random_integers(1, 10, size=(3, 3))


In [12]:
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
matrix

array([[ 5,  9,  5],
       [ 2, 10,  9],
       [ 3,  4,  9]])

In [5]:
identity_matrix = 3 * identity_matrix
identity_matrix

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [6]:
print(matrix * 3)

[[15 27 15]
 [ 6 30 27]
 [ 9 12 27]]


In [7]:
print(identity_matrix @ matrix)
print('')
print(matrix @ identity_matrix)



[[15 27 15]
 [ 6 30 27]
 [ 9 12 27]]

[[15 27 15]
 [ 6 30 27]
 [ 9 12 27]]
