In [2]:
import numpy as np
import pandas as pd
import random

In [3]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
df = pd.DataFrame(data)

In [4]:
df

animal  age  visits priority
0    cat  2.5       1      yes
1    cat  3.0       3      yes
2  snake  0.5       2       no
3    dog  NaN       3      yes
4    dog  5.0       2       no
5    cat  2.0       3       no
6  snake  4.5       1       no
7    cat  NaN       1      yes
8    dog  7.0       2       no
9    dog  3.0       1       no

In [5]:
names = ["Grace", "Henry", "Ivy", "Jack", "Kate", "Tina", "Uma", "Victor", "Wendy", "Xander", "Yvonne", "Zoe"]
array = np.array(names)

array

array(['Grace', 'Henry', 'Ivy', 'Jack', 'Kate', 'Tina', 'Uma', 'Victor',
       'Wendy', 'Xander', 'Yvonne', 'Zoe'], dtype='<U6')

In [6]:
empty_array = np.empty((2, 3))

empty_array

array([[1.22306926e-311, 1.22306926e-311, 1.22306926e-311],
       [1.22306926e-311, 1.22306926e-311, 1.22306926e-311]])

In [7]:
array_zeros = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

array_zeros[0]
type(array_zeros[0][0])

numpy.int32

In [8]:
type(np.zeros((2, 2))[0][0])

numpy.float64

In [9]:
z = np.zeros(shape=(2, 4), dtype='str')
z

array([['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [10]:
np.linspace(1, 100, 101)

array([  1.  ,   1.99,   2.98,   3.97,   4.96,   5.95,   6.94,   7.93,
         8.92,   9.91,  10.9 ,  11.89,  12.88,  13.87,  14.86,  15.85,
        16.84,  17.83,  18.82,  19.81,  20.8 ,  21.79,  22.78,  23.77,
        24.76,  25.75,  26.74,  27.73,  28.72,  29.71,  30.7 ,  31.69,
        32.68,  33.67,  34.66,  35.65,  36.64,  37.63,  38.62,  39.61,
        40.6 ,  41.59,  42.58,  43.57,  44.56,  45.55,  46.54,  47.53,
        48.52,  49.51,  50.5 ,  51.49,  52.48,  53.47,  54.46,  55.45,
        56.44,  57.43,  58.42,  59.41,  60.4 ,  61.39,  62.38,  63.37,
        64.36,  65.35,  66.34,  67.33,  68.32,  69.31,  70.3 ,  71.29,
        72.28,  73.27,  74.26,  75.25,  76.24,  77.23,  78.22,  79.21,
        80.2 ,  81.19,  82.18,  83.17,  84.16,  85.15,  86.14,  87.13,
        88.12,  89.11,  90.1 ,  91.09,  92.08,  93.07,  94.06,  95.05,
        96.04,  97.03,  98.02,  99.01, 100.  ])

In [11]:
string_list = ["apple", "banana", "orange", "grape", "kiwi"]
integer_list = [1, 2, 3, 4, 5]

strs = np.array(string_list)
strs2 = np.array(["Ivy", "Jack", "Kate", "Tina", "Uma"])
strs_array = np.array([strs, strs2])

ints = np.array(integer_list)
ints = np.reshape(ints, (1, -1))

ints


array([[1, 2, 3, 4, 5]])

In [12]:
strs_array

array([['apple', 'banana', 'orange', 'grape', 'kiwi'],
       ['Ivy', 'Jack', 'Kate', 'Tina', 'Uma']], dtype='<U6')

In [13]:
merged_array = np.concatenate((strs_array, ints), axis=0)

merged_array

array([['apple', 'banana', 'orange', 'grape', 'kiwi'],
       ['Ivy', 'Jack', 'Kate', 'Tina', 'Uma'],
       ['1', '2', '3', '4', '5']], dtype='<U11')

In [14]:
movie_titles = ["The Godfather", "Inception", "Pulp Fiction", "The Shawshank Redemption", "The Dark Knight", "Forrest Gump"]
film_1d_array = np.array(movie_titles)
film_2d_array = np.array([movie_titles])

#### Ways of reshaping

In [15]:
np.reshape(film_1d_array, (3, 2))
film_1d_array.reshape(3, 2)
film_1d_array[np.newaxis, :]
film_1d_array[:, np.newaxis]
np.expand_dims(film_1d_array, axis=1)

array([['The Godfather'],
       ['Inception'],
       ['Pulp Fiction'],
       ['The Shawshank Redemption'],
       ['The Dark Knight'],
       ['Forrest Gump']], dtype='<U24')

#### Slicing

In [16]:
film_1d_array.reshape(1, -1)[:]

array([['The Godfather', 'Inception', 'Pulp Fiction',
        'The Shawshank Redemption', 'The Dark Knight', 'Forrest Gump']],
      dtype='<U24')

In [17]:
rand_int_matrix = np.random.randint(1, 11, size=(3, 5))
rand_int_matrix

array([[ 1,  1,  4,  9,  3],
       [10,  6,  3,  4,  8],
       [10,  2,  1,  3,  9]])

In [18]:
rand_int_matrix[1:3, 3:]

array([[4, 8],
       [3, 9]])

In [19]:
rand_int_matrix[(rand_int_matrix > 5) & (rand_int_matrix < 8)]

array([6])

In [20]:
np.nonzero(rand_int_matrix > 8)

(array([0, 1, 2, 2], dtype=int64), array([3, 0, 0, 4], dtype=int64))

### NO COPY AT ALL

### SHALLOW COPY (VIEW)
1. Views and initial arrays share the same data.
2. Chaning views' data changes the initial data.

In [21]:
states_matrix = np.array([
    ["Alabama", "Alaska", "Arizona", "Arkansas", "California"],
    ["Colorado", "Connecticut", "Delaware", "Florida", "Georgia"],
    ["Hawaii", "Idaho", "Illinois", "Indiana", "Iowa"],
    ["Kansas", "Kentucky", "Louisiana", "Maine", "Maryland"]
])
states_matrix

array([['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California'],
       ['Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia'],
       ['Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa'],
       ['Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland']],
      dtype='<U11')

In [22]:
view1 = states_matrix[-3:, -3:]
view1[:] = 'XXX'
view1

array([['XXX', 'XXX', 'XXX'],
       ['XXX', 'XXX', 'XXX'],
       ['XXX', 'XXX', 'XXX']], dtype='<U11')

In [23]:
view2 = view1[-2:, -2:]
view2[:] = 'YYY'
view2

array([['YYY', 'YYY'],
       ['YYY', 'YYY']], dtype='<U11')

In [24]:
states_matrix

array([['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California'],
       ['Colorado', 'Connecticut', 'XXX', 'XXX', 'XXX'],
       ['Hawaii', 'Idaho', 'XXX', 'YYY', 'YYY'],
       ['Kansas', 'Kentucky', 'XXX', 'YYY', 'YYY']], dtype='<U11')

### Python vs NumPy indexing

In [25]:
turkish_names_list = ["Ahmet", "Ayşe", "Mehmet", "Fatma", "Mustafa", "Zeynep"]
turkish_names_list

['Ahmet', 'Ayşe', 'Mehmet', 'Fatma', 'Mustafa', 'Zeynep']

In [26]:
turkish_names_array = np.array(turkish_names_list)
turkish_names_array

array(['Ahmet', 'Ayşe', 'Mehmet', 'Fatma', 'Mustafa', 'Zeynep'],
      dtype='<U7')

In [27]:
turkish_names_list[:] = 'x'
turkish_names_list

['x']

In [28]:
turkish_names_array[:] = 'x'
turkish_names_array

array(['x', 'x', 'x', 'x', 'x', 'x'], dtype='<U7')

### DEEP COPY
1. Allows to make completely independent object (array)
2. Allows to release initial object (array) from the memory

#### (Jupyter truncating the output)

In [29]:
np.arange(1, 10000)

array([   1,    2,    3, ..., 9997, 9998, 9999])

In [58]:
v1 = np.ones(2).reshape(1, -1)
v1

v2 = np.array([3, 4]).reshape(1, -1)
v2

array([[3, 4]])

In [67]:
m1 = np.concatenate((v1, v2), axis=0)
m2 = np.concatenate((m1, m1), axis=1)
m3 = np.concatenate((m2, m2, m2, m2), axis=0)
m3


array([[1., 1., 1., 1.],
       [3., 4., 3., 4.],
       [1., 1., 1., 1.],
       [3., 4., 3., 4.],
       [1., 1., 1., 1.],
       [3., 4., 3., 4.],
       [1., 1., 1., 1.],
       [3., 4., 3., 4.]])

In [68]:
m3.shape

(8, 4)

In [72]:
m_random = np.random.randint(0, 22, size=(5, 7))
m_random

array([[ 8,  5, 12,  5, 14, 11, 21],
       [ 6,  9, 15,  4, 18, 10, 16],
       [18,  3, 17,  1,  4, 21, 15],
       [16, 20, 14,  1,  6, 13,  5],
       [ 4, 17,  6,  0, 21, 20, 11]])

#### Aggregate functions

In [80]:
m_random.sum() / m_random.size

11.057142857142857

In [81]:
m_random.mean()

11.057142857142857

In [83]:
m_random.sum(axis=0)

array([52, 54, 64, 11, 63, 75, 68])

#### Transpose a matrix

In [103]:
m_random

array([[ 8,  5, 12,  5, 14, 11, 21],
       [ 6,  9, 15,  4, 18, 10, 16],
       [18,  3, 17,  1,  4, 21, 15],
       [16, 20, 14,  1,  6, 13,  5],
       [ 4, 17,  6,  0, 21, 20, 11]])

In [107]:
m_random.T

array([[ 8,  6, 18, 16,  4],
       [ 5,  9,  3, 20, 17],
       [12, 15, 17, 14,  6],
       [ 5,  4,  1,  1,  0],
       [14, 18,  4,  6, 21],
       [11, 10, 21, 13, 20],
       [21, 16, 15,  5, 11]])

#### Reverse the matrix/vector/row/column order

In [119]:
alphabet_matrix = np.array([
    ['A', 'B', 'C', 'D', 'E'],
    ['F', 'G', 'H', 'I', 'J'],
    ['K', 'L', 'M', 'N', 'O'],
    ['P', 'Q', 'R', 'S', 'T'],
    ['U', 'V', 'W', 'X', 'Y']
])
alphabet_matrix

array([['A', 'B', 'C', 'D', 'E'],
       ['F', 'G', 'H', 'I', 'J'],
       ['K', 'L', 'M', 'N', 'O'],
       ['P', 'Q', 'R', 'S', 'T'],
       ['U', 'V', 'W', 'X', 'Y']], dtype='<U1')

In [127]:
# Reverse a row
alphabet_matrix[3] = np.flip(alphabet_matrix[3])
# Reverse a column
alphabet_matrix[:, 2] = np.flip(alphabet_matrix[:, 2])
alphabet_matrix

array([['A', 'B', 'W', 'D', 'E'],
       ['F', 'G', 'R', 'I', 'J'],
       ['K', 'L', 'M', 'N', 'O'],
       ['T', 'S', 'H', 'Q', 'P'],
       ['U', 'V', 'C', 'X', 'Y']], dtype='<U1')

#### Flattening the array:
1. with .flaten() - creates a deep copy
2. with .ravel() - creates a view

#### Quick dockstrings with '?'

In [137]:
alphabet_matrix?

Type:        ndarray
String form:
[['A' 'B' 'W' 'D' 'E']
 ['F' 'G' 'R' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['T' 'S' 'H' 'Q' 'P']
 ['U' 'V' 'C' 'X' 'Y']]
Length:      5
File:        c:\users\szymo\desktop\coding\jupyter\my_venv\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __ne